Add IBM Cloud Databases list and backups list fetchers
ComplianceAsCode/auditree-arboretum pull request #44
Opened 2021-01-11 18:58 UTC by Parthakumar-Roy

- [x] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](../blob/master/DCO1.1.txt)

## What

Migrate IBM Cloud Databases fetcher for account specific list of databases and backups list.

## Why

Audits often request evidence to check whether databases are regularly being backed up.

## How

REST api calls will be made to the resource controller and IBM Cloud databases end points.

## Test

Local testing to be done to verify evidence being created.

## Context

https://github.com/ComplianceAsCode/auditree-arboretum/issues/43

2021-01-12 15:39 UTC, Parthakumar-Roy commented
- picked a more descriptive `ibm_cloud_databases` for the source code directory, but left it at `icd` for the locker repo for backward compatibility.
 - as of this writing, the evidence for the list of databases is now going to change to a list of json objects, one per `resource_group_id` (previously it was the json object itself).
 ```
[
 {
  "next_url": null,
  "resources": [
    {
      "account_id": "...",
      "allow_cleanup": false,
      "controlled_by": "",
      "created_at": "2018-10-10T15:50:48.744687589Z",
      "created_by": "",
      "crn": "crn:v1:bluemix:public:databases-for-postgresql:us-south:a/...::",
       ...
      "resource_group_id": "...",
       ...
    },
    ...
   ],
  "rows_count": 13
 },
 {
  ...
 },
...
]
```
 - as of this writing, the evidence for the list of backups is still a list of the backup objects, no attempt has been made to make it a dictionary of backups list separated by `resource_group_id`.
 ```
[
  {
    "created_at": "2020-11-30T23:31:19.000Z",
    "deployment": {
      "id": "crn:v1:bluemix:public:databases-for-postgresql:us-south:a/...::",
      "version": "10"
    },
    "deployment_id": "crn:v1:bluemix:public:databases-for-postgresql:us-south:a/...::",
    "id": "crn:v1:bluemix:public:databases-for-postgresql:us-south:a/...:backup:...",
    "is_downloadable": false,
    "is_restorable": true,
    "status": "completed",
    "type": "scheduled"
  },
  ...
]
```
 - followed the `fetch_cluster_list` approach on how to remove dependency on `ibmcloud_tools`

2021-01-14 15:47 UTC, alfinkel requested changes
Pausing...

It looks like you may be adding functionality, so it's not a straight up migration of these fetchers.  If that's what you're doing then your README write up needs to be accurate as to this new behavior for these fetchers.  Can you clean up the README and then we can resume review?

Thanks.

2021-01-14 15:47 UTC, alfinkel commented on arboretum/ibm_cloud_databases/README.md
> +validate the configuration and ensure smooth execution of an auditree instance.
Remove this sentence: `They validate the configuration and ensure smooth execution of an auditree instance.`

2021-01-14 15:47 UTC, alfinkel commented on arboretum/ibm_cloud_databases/fetchers/fetch_backups.py
> +# -*- coding:utf-8; mode:python -*-
You're missing the copyright header here.

2021-01-14 15:47 UTC, alfinkel commented on CHANGES.md
> +- [ADDED] IBM Cloud Databases list and backups list fetchers added.
```suggestion
# [0.8.0](https://github.com/ComplianceAsCode/auditree-arboretum/releases/tag/v0.8.0)

- [ADDED] IBM Cloud Databases list fetcher added.
- [ADDED] IBM Cloud Databases backups fetcher added.
- [ADDED] Folder hierarchy for IBM Cloud Databases fetchers, checks, and harvest reports added.
```

2021-01-14 15:47 UTC, alfinkel commented on arboretum/ibm_cloud_databases/README.md
> +* Behavior: Access [IBM Cloud API][ibm-cloud-api] details of the databases as a JSON. TTL for evidence is set to 1 day.
```suggestion
* Behavior: Retrieve details about account specific IBM Cloud Databases. TTL for evidence is set to 1 day.
```

2021-01-14 15:47 UTC, alfinkel commented on arboretum/ibm_cloud_databases/README.md
> +    * List of objects representing the IBL Cloud accounts
```suggestion
    * List of dictionaries representing the IBM Cloud accounts
```

2021-01-14 15:47 UTC, alfinkel commented on arboretum/ibm_cloud_databases/README.md
> +    * Each object must have the following fields
```suggestion
    * Each dictionary must have the following fields
```

2021-01-14 15:47 UTC, alfinkel commented on arboretum/ibm_cloud_databases/README.md
> +        ```
I'd remove the example and simplify the bullet content.  You already provide the link to the command.

```suggestion
      * `resource_group_id` - the resource group associated with the account.
         * To obtain the resource group execute the [IBM Cloud resource groups command][ic-resource-groups].
```

2021-01-14 15:47 UTC, alfinkel commented on arboretum/ibm_cloud_databases/README.md
> +      * `account_name` - an arbitrary name identifying the IBM Cloud account, used to match to the token provided in the
```suggestion
      * `account_name` - an arbitrary name as a string identifying the IBM Cloud account, used to match to the token provided in the
```

2021-01-14 15:47 UTC, alfinkel commented on arboretum/ibm_cloud_databases/README.md
> +      * `resource_group_id` - the resource group associated with the above account name, output of [running the ibmcloud resource groups command][ic-resource-groups] while logged in to an IBM Cloud a
```suggestion
      * `resource_group_id` - the resource group as a string associated with the above account name, output of [running the ibmcloud resource groups command][ic-resource-groups] while logged in to an IBM Cloud account.
```

2021-01-14 15:47 UTC, alfinkel commented on arboretum/ibm_cloud_databases/README.md
> +                                   ]
This isn't valid JSON and renders as such in GH.  This example also has resource_group_id as a list of strings whereas the description of it is that it should be a string.  Assuming string...

```suggestion
              "resource_group_id": "bcdef0123456789fedcba1234567890a"
```

2021-01-14 15:47 UTC, alfinkel commented on arboretum/ibm_cloud_databases/README.md
> +  ```
OK now it seems like you're introducing new functionality here?  If you're looking to support this new functionality and deprecate the old one where you have a single resource group as a string that's fine but you don't need to include the "backward compatibility" version in the docs.

2021-01-15 16:08 UTC, Parthakumar-Roy commented
Local test results added to the top - it raises the question of whether 404 errors should abort creation of the backups evidence.

2021-01-15 17:37 UTC, alfinkel commented
What's the question exactly?

2021-01-19 15:23 UTC, Parthakumar-Roy commented
> What's the question exactly?

When fetch_backups.py iterates through a list of databases, if it gets a 404 from any of the backup URL's `https://api.<region>.databases.cloud.ibm.com/v4/ibm/deployments/<database_crn_escaped>/backups`, the fetcher aborts. Is this acceptable behavior?

2021-06-07 20:55 UTC, alfinkel commented
Closing due to inactivity

2021-06-07 20:55 UTC, closed without merging